export const SELECTED_FILM = "SELECTED_FILM"
export const REMOVE_SELECTED_FILM = 'REMOVE_SELECTED_FILM'

export const FETCH_FILMS_LIST = 'FETCH_FILMS_LIST'
export const FETCH_FILM_DETAILS = 'FETCH_FILM_DETAILS'

export const ERROR_TRUE = 'ERROR_TRUE'
export const ERROR_FALSE = 'ERROR_FALSE'

