export const SELECTED_FILM = "SELECTED_FILM"
export const REMOVE_SELECTED_FILM = 'REMOVE_SELECTED_FILM'

export const FETCH_FILMS_LIST_REQUEST = 'FETCH_FILMS_LIST_REQUEST'
export const FETCH_FILMS_LIST_SUCCESS = 'FETCH_FILMS_LIST_SUCCESS'
export const FETCH_FILMS_LIST_FAILURE = 'FETCH_FILMS_LIST_FAILURE'

export const FETCH_FILM_DETAILS_REQUEST = 'FETCH_FILM_DETAILS_REQUEST'
export const FETCH_FILM_DETAILS_SUCCESS = 'FETCH_FILM_DETAILS_SUCCESS'
export const FETCH_FILM_DETAILS_FAILURE = 'FETCH_FILM_DETAILS_FAILURE'

export const ERROR_TRUE = 'ERROR_TRUE'
export const ERROR_FALSE = 'ERROR_FALSE'

